# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "junglami-yocto"
BBFILE_PATTERN_junglami-yocto = "^${LAYERDIR}/"
BBFILE_PRIORITY_junglami-yocto = "6"
LAYERDEPENDS_junglami-yocto = "core"
LAYERSERIES_COMPAT_junglami-yocto = "scarthgap"